<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>RentalApp.Domain</RootNamespace>
    <AssemblyName>RentalApp.Domain</AssemblyName>
  </PropertyGroup>

</Project>
